ДЗ/HomeWork/HomeWork/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('carshowroom.urls'))
]

ДЗ/HomeWork/carshowroom/urls.py
from django.urls import path
from . import views

app_name = 'carshowroom'
urlpatterns = [
    path('', views.cars, name ="home"),
    path('report/',views.report, name = "report"),
    path('suppliers/', views.supply, name="supply"),
]

ДЗ/HomeWork/carshowroom/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Supplier(models.Model):
    name = models.CharField('Название поставщика' ,max_length=50)
    field = models.CharField('Поставляемый товар' ,max_length=500)
    adress = models.CharField('Адрес поставщика' ,max_length=500, default="")
    def __str__(self):
        return self.name

class Dealer(models.Model):
    name = models.CharField('Марка автомобиля' ,max_length=50)
    number = models.CharField('Контактный номер' ,max_length=50, default=1)
    suppliers= models.ManyToManyField(Supplier, blank=True)
    def __str__(self):
        return self.name

class Car_model(models.Model):
    dealer = models.ForeignKey(Dealer, on_delete=models.CASCADE)
    name = models.CharField('Название модели',max_length=50)
    quantity = models.IntegerField('Количество' ,max_length=1000)
    price = models.IntegerField('Цена' ,max_length=100000)
    description = models.CharField('Описание' ,max_length=1000)
    def __str__(self):
        return self.name

ДЗ/HomeWork/carshowroom/views.py
import operator

from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from .models import Dealer
from .models import Car_model
from .models import Supplier

def index(request):
    auto_list = Dealer.objects.all()
    context = {'auto_list': auto_list}
    return render(request, 'carshowroom/main.html', context)

def cars(request):
    auto = Car_model.objects.all().select_related('dealer')
    dealers = Dealer.objects.all()
    dealersstr = []
    for d in dealers:
        dealersstr.append(d)
    order = {key: i for i, key in enumerate(dealersstr)}
    auto_model = sorted(auto, key=lambda auto: order.get(auto.dealer, 0))
    return render(request, 'carshowroom/main.html',{'auto_model': auto_model})

def report(request):
    auto = Car_model.objects.all().select_related('dealer')
    dealers = Dealer.objects.all()
    dealersstr = []
    for d in dealers:
        dealersstr.append(d)
    order = {key: i for i, key in enumerate(dealersstr)}
    auto_model = sorted(auto, key=lambda auto: order.get(auto.dealer, 0))
    return render(request, 'carshowroom/view.html',{'auto_model': auto_model})

def supply(request):
    dealers = Dealer.objects.all().prefetch_related('suppliers')
    return render(request, 'carshowroom/supply.html',{'dealers': dealers})

ДЗ/HomeWork/carshowroom/templates/carshowroom/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js" integrity="sha512-d9xgZrVZpmmQlfonhQUvTR7lMPtO7NkZMkA0ABN3PHCbKA5nqylQ/yWlFAyY6hYgdF1Qh6nYiuADWwKB4C2WSw==" crossorigin="anonymous"></script>
    <script src="graph.js"></script>
</head>
<body>
<nav class="navbar navbar-light bg-dark" >
    <nav class="navbar navbar-expand-lg navbar-dark bg-light rounded" aria-label="Twelfth navbar example">
      <div class="container-fluid" >
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample10" aria-controls="navbarsExample10" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample10">
          <ul class="navbar-nav" >
          <ul class="navbar-nav" >
            <li class="nav-item active">
                <form class="container-fluid justify-content-start">
                  <button class="btn btn-outline-dark" type="button" onClick='location.href="{% url 'carshowroom:home'%}"'>Купи квартирку</button>
                </form>
            </li>
            <li class="nav-item">
                <form class="container-fluid justify-content-start">
                  <button class="btn btn-outline-dark" type="button" onClick='location.href="{% url 'carshowroom:report' %}"'>Отчет о всем жилье на продаже</button>
                </form>
            </li>
          </ul>
        </div>
      </div>
    </nav>
	</nav>
{% block content %}{% endblock %}
</body>
</html>

ДЗ/HomeWork/carshowroom/templates/carshowroom/main.html
{% extends 'carshowroom/base.html' %}

{% block title %}
Главная страница
{% endblock %}
{% block content %}
        <div class="container ">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 ">
                {% for model in auto_model %}
                <div class="col mt-4">
                    <div class="card shadow"style="background-color: #d7d7d7;">
                        <div class="card-body">
                            <h4 class="p-1 mb-0 bg-dark text-white card-title mx-auto text-center">{{ model.dealer.name }}</h4>
                            <p class="p-1 bg-dark text-white mx-auto text-center">{{model.name}}</p>
                            <p><strong>Продается:</strong><span class="font-monospace "> {{model.quantity}}</span></p>
                            <p><strong>Цена жилья:</strong> <span class="font-monospace ">{{model.price}}$</span></p>
                            <p><strong>Общее описание:</strong> <span class="font-monospace ">{{model.description}}</span></p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
{% endblock %}

ДЗ/HomeWork/carshowroom/templates/carshowroom/supply.html
{% extends 'carshowroom/base.html' %}

{% block title %}
Риэлторская компания
{% endblock %}
{% block content %}
        <div class="container">
            <div class="row >
                {% for d in dealers %}
                <div class="col mt-4">
                    <div class="card shadow ">
                        <div class="card-body">
                            <h5 class="p-3 mb-0 bg-dark text-white card-title mx-auto text-center">{{ d.name }}</h5>
                            <p class = "p-2 mb-auto mx-auto text-center"><strong>Контактный номер:</strong> {{d.number}}</p>
                            <div class="mb-0 mx-auto ">
                                {% for supplier in d.suppliers.all %}
                                <p class = "p-1 mb-0 bg-dark text-white mx-auto text-center"><strong class="pb-1 ">Риэлторская компания: {{ supplier }}</strong></p>
                                    <p class = "ps-2 mb-1 mx-auto text-center"><strong class="pb-1 ">Поставляемый продукт:</strong> {{ supplier.field }}</p>
                                    <p class = "ps-2 mb-1 mx-auto text-center"><strong class="pb-1 ">Адрес риэлторской компании:</strong> {{ supplier.adress }}</p>
                                {% endfor %}
                            </p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
{% endblock %}

ДЗ/HomeWork/carshowroom/templates/carshowroom/view.html
{% extends 'carshowroom/base.html' %}

{% block title %}
Отчеты
{% endblock %}

{% block content %}
<div class ="container">
    <h1>Отчет о всем жилье на продаже: {{ header }}</h1>
    {% if auto_model %}
        <table class="table table-hover table-striped table-bordered border-dark table-sm mx-auto">
            <tr class="text-center "><th>Тип жилья</th><th>Риэлторская компания</th><th>Номер производителя</th><th>Цена</th><th>Количество</th><th>Описание</th></tr>
            {% for model in auto_model %}
                <tr class="text-center"><td>{{ model.name }}</td><td>{{ model.dealer }}</td><td>{{ model.dealer.number }}</td><td>{{ model.price }}$</td>
                <td>{{ model.quantity }}</td><td>{{ model.description }}</td></tr>
            {% endfor %}
        </table>
    {% else %}
        <p>Database is empty.</p>
    {% endif %}
</div>
{% endblock %}